### ISSUE TITLE
get_*_price doesn't use specified currency

### ISSUE THREAD

**Issue by zoomorph** [coinbase/coinbase-python#36]
It appears to mostly return in CAD instead of USD, despite asking for USD:

```
In [9]: client.get_spot_price(currency_pair='BTC-USD')
Out[9]:
<APIObject @ 0x38b7880> {
  "amount": "1386.45",
  "currency": "CAD"
}
```

Although sometimes it returns USD....

For the time being I'm using the REST API without authentication as a workaround.

**Comment by JohnLZeller** [comment]
@zoomorph does this still happen for you? I'm seeing this work as expected both in version `2.0.6`, and on a build of `master`.

**Comment by pearsonkyle** [comment]
I'm experiencing a similar issue. I can't see to pass a custom currency_pair to get_spot_price, it will always default to BTC-USD for me.

**Comment by achampion** [comment]
Wasn't this fixed with #30 ?

**Comment by parth-choudhary** [comment]
Still facing the issue, when asking for ETH price it sometimes returns ETH otherwise USD.

**Comment by CaptainEgregious** [comment]
I'm facing a similar issue, get_buy_price() returns BTC-GBP which is my account setting rather than the specified currency code BTC-USD.

**Comment by keith24** [comment]
Possibly not working to due to #35 and #30.

**Comment by theonewolf** [comment]
I am definitely getting EUR back in spite of requesting USD.  The odd thing is that occasionally it actually returns USD.  I am not sure why, perhaps there is some bad caching going on now with the massive and rapid growth in user base?

**Comment by raaaaaymond** [comment]
Same issue. The currency I get seems to be a random choice between USD, GBP, and EUR, and the `currency` argument seems to be completely ignored. Python 3.6.2, Coinbase 2.0.6.

**Comment by parth-choudhary** [comment]
I just ditched using coinbase package and started using urllib to fetch prices.

Working fine for 2 months now.
Here is the code:

`http = urllib3.PoolManager()
 r = http.request('GET', 'https://api.coinbase.com/v2/exchange-rates?currency=ETH')
 rate = json.loads(r.data.decode('utf-8'))`

**Comment by theonewolf** [comment]
@raaaaaymond I was wondering if it might be some sort of caching layer gone wrong.  But, maybe it's just the client library not properly working with a newer API.

Have you tried the `master` branch?

**Comment by djdeniro** [comment]
Not working!

**Comment by sds** [comment]
We recently released a new version of this library. Please try it out and open a new issue if you're still encountering problems. Thanks!
