### ISSUE TITLE
Visual Studio Dependency Issue?

### ISSUE THREAD

**Issue by clairmont32** [coinbase/coinbase-python#61]
Greetings,

When I tried to install the library with pip and easy_install it gave me an error saying I didn't have a VS exe on my machine. Error is below... but this sounds weird considering all of my past Python dev hasn't given me any issues with a Microsoft specific update. 

`Running pycrypto-2.6.1\setup.py -q bdist_egg --dist-dir C:\Users\matth\AppData\Local\Temp\easy_install-rv4q42w9\pycrypto-2.6.1\egg-dist-tmp-zx9qqsbw
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
winrand.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(26): error C2061: syntax error: identifier 'intmax_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(27): error C2061: syntax error: identifier 'rem'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(27): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(28): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(30): error C2061: syntax error: identifier 'imaxdiv_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(30): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(40): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2146: syntax error: missing ')' before identifier '_Number'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2061: syntax error: identifier '_Number'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(41): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(42): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(45): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2146: syntax error: missing ')' before identifier '_Numerator'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2061: syntax error: identifier '_Numerator'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(46): error C2059: syntax error: ','
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(48): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(50): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(56): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(63): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(69): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(76): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(82): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(89): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\inttypes.h(95): error C2143: syntax error: missing '{' before '__cdecl'
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2`

**Comment by dcanones** [comment]
I am having exactly the same error. Have Visual C++ 2015 installed (via Build Essentials Tools). Any ideas? Do I need to install full version of Visual Studio IDE?

**Comment by robfromdublin** [comment]
Same error for me.  Any resolutions available?

**Comment by robfromdublin** [comment]
By following the answer in [this SO question](https://stackoverflow.com/questions/41843266/microsoft-windows-python-3-6-pycrypto-installation-error), I resolved the issue.  In short, steps are:

1. Open command prompt with admin privileges
2. Run vsvars32.bat from your version of VC
3. set CL=-FI"%VCINSTALLDIR%\INCLUDE\stdint.h"
4. pip install coinbase

**Comment by dcanones** [comment]
Hi guys!

The problem is with pycrypto dependency and I solved in the most silly way I could imagine. Just made a 'conda install pycrypto' (should work also with pip) before installing coinbase... just works, no more C++ compiler or VS errors. Hope it helps!

**Comment by jdimstrnate** [comment]
I have tried all suggestions in detail and pycrypto is still broken.

**Comment by sds** [comment]
This sounds like an issue with development dependencies for working with `pycrypto` on Windows. Going to close as this is outside the scope of this package.
